on: [push]

jobs:
  github_automation_job:
    runs-on: ubuntu-latest
    name: Runs GitHub Automation
    steps:
      - name: Runs GitHub Automation script
        id: gh_auto
        uses: ptrsmrn/test@v22
        with:
          pat-var: ${{ secrets.PAT }}
      - name: Get the output of the script
        run: echo "The output is ${{ steps.gh_auto.outputs.unused_output_param }}"
