on: [push]

jobs:
  github_automation_job:
    runs-on: ubuntu-latest
    name: Runs GitHub Automation
    steps:
      - name: Runs GitHub Automation script
        id: gh_auto
        uses: ptrsmrn/test@v23
        with:
          pat-var: ${{ secrets.PAT }}
